#!/usr/bin/python2
 
import os
import sys
import traceback
 
import hooking
 
'''
Syntax:
hana=1 (value doesn't matter)

The VM must be configured as High Performance with 1GB hugepages.
For that the following kernel boot line is required for the hypervisor:

"default_hugepagesz=1GB hugepagesz=1GB hugepages=[# hugepages needed]"

In addition the "hugepages" custom property needs to be set to 1048576.
'''
 
 
if 'hana' in os.environ:
    try:
        domxml = hooking.read_domxml()
        domain = domxml.getElementsByTagName('domain')[0]
        if not len(domain.getElementsByTagName('memoryBacking')):
            sys.stderr.write('hugepages: VM is no High Performance VM\n')
            sys.exit(0)
 
        if len(domain.getElementsByTagName('cpu')):
            cpu = domain.getElementsByTagName('cpu')[0]
            feature_tsc = domxml.createElement('feature')
            feature_tsc.setAttribute('policy', 'require')
            feature_tsc.setAttribute('name', 'invtsc')
            cpu.appendChild(feature_tsc)

        hooking.write_domxml(domxml)
    except Exception:
        sys.stderr.write('highperf hook: [unexpected error]: %s\n' %
                         traceback.format_exc())
        sys.exit(2)
